### ISSUE TITLE
NameError: global name 'recompile' is not defined

### ISSUE THREAD

**Issue by TheseArmsRSnakes** [unixrox/prebellico#6]
```
Cisco HSRP is spoken here.
Traceback (most recent call last):
  File "prebellico.py", line 1579, in <module>
    sniff.loop(0, inspectProto)
  File "prebellico.py", line 259, in inspectProto
    udpDiscovery(header,data)
  File "prebellico.py", line 626, in udpDiscovery
    hsrpPacketFilterRegex = recompile('[a-zA-Z0-9*]*')# Regex to yank data within snmp string data.
NameError: global name 'recompile' is not defined
```

**Comment by unixrox** [comment]
Thank you so much for catching this and contributing to the success of this tool! I cannot tell you how frustrating it was when this IDE removed all of my periods a few releases ago. I tried to catch all instances of this but it looks like I missed three instances of this. I believe I have addressed this with this release which is pushed to the master:
https://github.com/unixrox/prebellico/commit/64a253abc505834edc8b58e035178136d187fc32

Can you please confirm?

**Comment by TheseArmsRSnakes** [comment]
```
Cisco HSRP is spoken here.
Traceback (most recent call last):
  File "prebellico.py", line 1579, in <module>
    sniff.loop(0, inspectProto)
  File "prebellico.py", line 259, in inspectProto
    udpDiscovery(header,data)
  File "prebellico.py", line 627, in udpDiscovery
    hsrpTempData=hsrpPacketFilterRegexfindall(hsrpTempData)
NameError: global name 'hsrpPacketFilterRegexfindall' is not defined
```

**Comment by unixrox** [comment]
I have addressed that line with the following release which is committed to the master:
https://github.com/unixrox/prebellico/commit/c2d2b07c14b173b190f5981afe7bda488a8a9bf0

Can you please confirm?

**Comment by TheseArmsRSnakes** [comment]
Resolved. Closing out ticket.
